[package]
name = "rust-to-ts"
version = "0.2.2"
edition = "2021"
description = "Rust to TypeScript transpiler"

[dependencies]
regex = "1.10.6"
toml = "0.8.19"
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.127"
